<?php

namespace ScoutBundle\Repository;

/**
 * HouseLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
