<?php

namespace ScoutBundle\Repository;

/**
 * HouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $searchTerms
     * @return mixed
     */
    public function search($searchTerms)
    {
        /*return $this->createQueryBuilder('a')
        ->where('a.title LIKE :searchTerm OR a.metaTitle LIKE :searchTerm OR a.metaDescription LIKE :searchTerm OR a.content LIKE :searchTerm')
        ->setParameter('searchTerm', '%'.$searchTerm.'%')
        ->getQuery()
        ->execute();*/

        $qb = $this->createQueryBuilder('c');

        for ($i = 0; $i < count($searchTerms); $i++) {
            $term = $searchTerms[$i];
            if(!empty($term)){
                $qb->orWhere($qb->expr()->like('c.title', "?$i"));
                $qb->orWhere($qb->expr()->like('c.content', "?$i"));
                $qb->setParameter($i, '%' . $term . '%');
            }
        }

        return $qb->getQuery()->execute();
    }

}
