<?php

namespace ScoutBundle\Repository;

/**
 * HouseAmenityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseAmenityRepository extends \Doctrine\ORM\EntityRepository
{
}
