<?php

namespace ScoutBundle\Repository;

/**
 * HouseBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseBookingRepository extends \Doctrine\ORM\EntityRepository
{
}
