<?php

namespace ScoutBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandLordRepository extends \Doctrine\ORM\EntityRepository
{
}
