<?php

namespace ScoutBundle\Repository;

/**
 * PageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByLang($locale){
        return $this->createQueryBuilder('c')
            //->addSelect("p")
            ->join("c.lang","l")
            //->join("c.pages","p")
            ->where("l.locale = :locale")
            ->setParameter("locale",$locale)
            ->getQuery()->getResult();
    }

    public function findAllByLang($locale){
        return $this->createQueryBuilder('c')
            ->addSelect("p")
            ->join("c.lang","l")
            ->join("c.pages","p")
            ->where("l.locale = :locale")
            ->setParameter("locale",$locale)
            ->getQuery()->getResult();
    }
}
