<?php

namespace ScoutBundle\Repository;

/**
 * RoomSeekerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomSeekerRepository extends \Doctrine\ORM\EntityRepository
{
}
