house_index:
    path:     /house
    defaults: { _controller: "ScoutBundle:House:index" }
    methods:  GET

house_show:
    path:     /{id}/house_show
    defaults: { _controller: "ScoutBundle:House:show" }
    methods:  GET

house_list:
    path:     /admin/house
    defaults: { _controller: "ScoutBundle:House:list" }
    methods:  GET

house_detail:
    path:     /admin/{id}/house_detail
    defaults: { _controller: "ScoutBundle:House:detail" }
    methods:  GET

house_new:
    path:     /admin/house_new
    defaults: { _controller: "ScoutBundle:House:new" }
    methods:  [GET, POST]

house_edit:
    path:     /admin/{id}/house_edit
    defaults: { _controller: "ScoutBundle:House:edit" }
    methods:  [GET, POST]

house_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScoutBundle:House:delete" }
    methods:  DELETE
