houselocation_index:
    path:     /location
    defaults: { _controller: "ScoutBundle:HouseLocation:index" }
    methods:  GET

houselocation_show:
    path:     /{id}/houselocation_show
    defaults: { _controller: "ScoutBundle:HouseLocation:show" }
    methods:  GET

houselocation_list:
    path:     /admin/location
    defaults: { _controller: "ScoutBundle:HouseLocation:list" }
    methods:  GET

houselocation_detail:
    path:     /admin/{id}/houselocation_sdetail
    defaults: { _controller: "ScoutBundle:HouseLocation:detail" }
    methods:  GET

houselocation_new:
    path:     /admin/houselocation_new
    defaults: { _controller: "ScoutBundle:HouseLocation:new" }
    methods:  [GET, POST]

houselocation_edit:
    path:     /admin/{id}/houselocation_edit
    defaults: { _controller: "ScoutBundle:HouseLocation:edit" }
    methods:  [GET, POST]

houselocation_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScoutBundle:HouseLocation:delete" }
    methods:  DELETE
