_index:
    path:     /
    defaults: { _controller: "ScoutBundle:House:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "ScoutBundle:House:show" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "ScoutBundle:House:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "ScoutBundle:House:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScoutBundle:House:delete" }
    methods:  DELETE
