image_index:
    path:     /admin/image
    defaults: { _controller: "ScoutBundle:Image:index" }
    methods:  GET

image_show:
    path:     /admin/{id}/image_show
    defaults: { _controller: "ScoutBundle:Image:show" }
    methods:  GET

image_new:
    path:     /admin/image_new
    defaults: { _controller: "ScoutBundle:Image:new" }
    methods:  [GET, POST]

image_edit:
    path:     /admin/{id}/image_edit
    defaults: { _controller: "ScoutBundle:Image:edit" }
    methods:  [GET, POST]

image_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScoutBundle:Image:delete" }
    methods:  DELETE
