mailinglist_index:
    path:     /admin/mailinglist
    defaults: { _controller: "ScoutBundle:MailingList:index" }
    methods:  GET

mailinglist_show:
    path:      /admin/{id}/mailinglist_show
    defaults: { _controller: "ScoutBundle:MailingList:show" }
    methods:  GET

mailinglist_new:
    path:      /admin/mailinglist_new
    defaults: { _controller: "ScoutBundle:MailingList:new" }
    methods:  [GET, POST]

mailinglist_edit:
    path:      /admin/{id}/mailinglist_edit
    defaults: { _controller: "ScoutBundle:MailingList:edit" }
    methods:  [GET, POST]

mailinglist_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScoutBundle:MailingList:delete" }
    methods:  DELETE
