settings_index:
    path:     /admin/settings
    defaults: { _controller: "AppBundle:Settings:index" }
    methods:  GET

settings_show:
    path:     /admin/{id}/settings_show
    defaults: { _controller: "AppBundle:Settings:show" }
    methods:  GET

settings_display:
    path:     /{id}/settings
    defaults: { _controller: "AppBundle:Settings:display" }
    methods:  GET

settings_new:
    path:     /admin/settings_new
    defaults: { _controller: "AppBundle:Settings:new" }
    methods:  [GET, POST]

settings_edit:
    path:     /admin/{id}/settings_edit
    defaults: { _controller: "AppBundle:Settings:edit" }
    methods:  [GET, POST]

settings_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Settings:delete" }
    methods:  DELETE
