villacategory_index:
    path:     /villacategory
    defaults: { _controller: "AppBundle:VillaCategory:index" }
    methods:  GET

villacategory_show:
    path:     /{id}/villacategory_show
    defaults: { _controller: "AppBundle:VillaCategory:show" }
    methods:  GET

villacategory_list:
    path:     /admin/villacategory_index
    defaults: { _controller: "AppBundle:VillaCategory:list" }
    methods:  GET

villacategory_detail:
    path:     /admin/{id}/villacategory_show
    defaults: { _controller: "AppBundle:VillaCategory:detail" }
    methods:  GET

villacategory_new:
    path:     /admin/villacategory_new
    defaults: { _controller: "AppBundle:VillaCategory:new" }
    methods:  [GET, POST]

villacategory_edit:
    path:     /admin/{id}/villacategory_edit
    defaults: { _controller: "AppBundle:VillaCategory:edit" }
    methods:  [GET, POST]

villacategory_delete:
    path:     /{id}/villacategory_delete
    defaults: { _controller: "AppBundle:VillaCategory:delete" }
    methods:  DELETE
