villaservice_index:
    path:     /admin/villaservice
    defaults: { _controller: "AppBundle:VillaService:index" }
    methods:  GET

villaservice_show:
    path:     /admin/{id}/villaservice_show
    defaults: { _controller: "AppBundle:VillaService:show" }
    methods:  GET

villaservice_new:
    path:     /admin/villaservice_new
    defaults: { _controller: "AppBundle:VillaService:new" }
    methods:  [GET, POST]

villaservice_edit:
    path:     /admin/{id}/villaservice_edit
    defaults: { _controller: "AppBundle:VillaService:edit" }
    methods:  [GET, POST]

villaservice_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:VillaService:delete" }
    methods:  DELETE
