<?php

namespace AppBundle\Repository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByLang($locale)
    {
        return $this->createQueryBuilder('p')
            ->join("p.lang","l")
            ->where("l.locale = :locale")
            ->setParameter("locale",$locale)
          
        ->setMaxResults(1)
        ->getQuery()->getSingleResult();

    }
    
}
