scout:
    resource: "@ScoutBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: "%app.locales%"


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /