# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     scoutBundle.eventListeners.localeRewriteListener:
          class: ScoutBundle\EventListener\LocaleRewriteListener
          arguments: ["@router", "%kernel.default_locale%", "%locale_supported%"]
          tags:
            - { name: kernel.event_subscriber }

     slugify:
          class: ScoutBundle\Service\Slugify
          tags:
            - { name: slugify, alias: slugify }


     common.listener.login:
          class: ScoutBundle\EventListener\LoginListener
          arguments: ["@router", "@security.token_storage", "@event_dispatcher", "@logger"]
          scope: request
          tags:
             - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

