<?php

namespace AppBundle\Repository;

/**
 * VillaBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillaBookingRepository extends \Doctrine\ORM\EntityRepository
{
}
