<?php

namespace AppBundle\Repository;

/**
 * VillaCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillaCategoryRepository extends \Doctrine\ORM\EntityRepository
{


    public function findAllByLang($locale){
        return $this->createQueryBuilder('c')
            //->addSelect("p")
            ->join("c.lang","l")
           // ->join("c.villacategories","p")
            ->where("l.locale = :locale")
            ->setParameter("locale",$locale)
            ->getQuery()->getResult();
    }

}
