<?php

namespace AppBundle\Repository;

/**
 * VillaServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillaServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
