<?php

namespace AppBundle\Repository;

/**
 * VillaAmenityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillaAmenityRepository extends \Doctrine\ORM\EntityRepository
{
}
