<?php

namespace AppBundle\Repository;

/**
 * VillaSurfaceAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillaSurfaceAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
