<?php

namespace AppBundle\Repository;

/**
 * VillaLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillaLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
